using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace TaskManagementSystem_WebApplication.Models
{
    public class ReportDetails
    {
        [Key]
        [DisplayName("Report id")]
        public int ReportID { get; set; }
        [DisplayName("Task id")]
        public int TaskID { get; set; }

        [DisplayName("Task name")]
        public string TaskTitle { get; set; }
        [DisplayName("Generated By")]
        public int GeneratedBy { get; set; }
        [DisplayName("Generated by")]
        public string GeneratedAdmin { get; set; }

        [DisplayName("Report name")]
        public string ReportName { get; set; }
        [DisplayName("Created Date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true, NullDisplayText = "N/A")]
        public DateTime? GeneratedOn { get; set; }
        [DisplayName("Report data")]
        public string ReportData { get; set; }

        public string ReportImage { get; set; }
    }
}